python rungpt2.py  --datadir='data/xsum/gpt2-large-adg-300'
python rungpt2.py  --datadir='data/xsum/gpt2-large-hc-300-bit1'
python rungpt2.py  --datadir='data/xsum/gpt2-large-hc-300-bit2'
python rungpt2.py  --datadir='data/xsum/gpt2-large-hc-300-bit3'
python rungpt2.py  --datadir='data/xsum/gpt2-large-hc-300-bit4'
python rungpt2.py  --datadir='data/xsum/gpt2-large-hc-300-bit5'